### ISSUE TITLE
Bug: PLUGIN_PATHS can span multiple lines

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-actions#10]
The output from python3 -m pelican --print-settings PLUGIN_PATHS can have mulitple lines if there is more than one path in the list.

https://github.com/apache/infrastructure-actions/blob/06fa613303528411ddb4b1da8a1d028781e7b81a/build-pelican/action.yml#L40

**Comment by gstein** [comment]
257e1056 shows how to load the pelicanconf.py and grab that value. I think we'll switch to this pattern.
