### ISSUE TITLE
The PLUGINS list can span several lines

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-actions#11]
The parsing does not allow for mulitple lines:

https://github.com/apache/infrastructure-actions/blob/06fa613303528411ddb4b1da8a1d028781e7b81a/build-pelican/action.yml#L49

It also assumes that plugin names will be delimited by single quotes.

**Comment by gstein** [comment]
257e1056 shows how to load the pelicanconf.py and grab that value. I think we'll switch to this pattern.
