### ISSUE TITLE
Continue on error should not be used unless absolutely necessary

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-actions#33]
https://github.com/apache/infrastructure-actions/blob/af378a87ed2697d6c7d37fdb22a91c86ad03580e/pelican/action.yml#L83

continue-on-error is a very blunt instrument, and should only be used if the step is completely optional.
That is not the case here.
For commands that can legitimately fail, one can use a conditional or something like 'command || true" to ignore the status

**Comment by dave2wave** [comment]
I had a similar feeling - if conditions like:
