### ISSUE TITLE
Regression: Presence of *.ezmd files won't be checked after initial conversion of pelicanconf.yaml

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-actions#4]
The conversion of pelicanconf.yaml to pelicanconf.py depends on an external setting, viz: the presence of any *.ezmd files:
https://github.com/apache/infrastructure-actions/blob/475d8f649ab3fa835cb9c79a44938d8d75a75ab3/pelican/migration/generate_settings.py#L158

This means that subsequent changes to the website source won't automatically be reflected in the build settings.

**Comment by gstein** [comment]
If a projects add .ezmd files, then they should add `asfreader` to the plugins.

The `generate_settings.py` script is a one-time migration to move a site, as it exists at that point in time, to the new GHA-based Pelican system. Future changes to the site content may require future tweaks to the config file.

**Comment by gstein** [comment]
https://github.com/search?q=org%3Aapache+path%3A**%2F*.ezmd&type=code

Shows three repositories with .ezmd files: www-site, template-site, and openwebbeans-site

**Comment by gstein** [comment]
The connection not obvious, yeah. .. Thank you!
