### ISSUE TITLE
What is the proper yaml for output branches 

### ISSUE THREAD

**Issue by dave2wave** [apache/infrastructure-actions#46]
I see the following in the action at https://github.com/apache/infrastructure-actions/blob/main/pelican/action.yml#L102-L104

This copies the `.asf.yaml` file.. This is not really what is needed:

For preview we need:
```
staging:
  profile: ~
  autostage: preview/*
```

and for branch `ash-site`:
```
publish:
  profile: ~
  whoami: asf-site
```

**Comment by dfoulks1** [comment]
the staging part of the .asf.yaml are branch specific aiui, so only the bits matching the `whoami` will be evaluated.

**Comment by dave2wave** [comment]
Thank you
