### ISSUE TITLE
generate_settings.py should not copy plugins

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-actions#7]
The script currently copies all the plugins to each website repo.

This will make it very hard to maintain the plugins.

**Comment by gstein** [comment]
Totally agree. I said exactly the same on Slack. We will not roll out GHA Pelican handling with copy-plugins, and will keep all plugins in a centrally-located single-source maintenance location.

**Comment by dfoulks1** [comment]
the workflow no longer copies plugins but uses `pelican --print-settings` to fetch plugins to the configured plugin path based on the pelicanconf.py
