### ISSUE TITLE
CURRENTYEAR needs to be dynamically generated

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-actions#8]
In the existing Pelican builds, CURRENTYEAR is regenerated every time the site is built.

However generate_settings replaces the variable reference ([year]) with a fixed value:

https://github.com/apache/infrastructure-actions/blob/50ca5458f5964fe051c745aa3e9a4cdf12077c0d/pelican/migration/generate_settings.py#L46

**Comment by dfoulks1** [comment]
it looks like we should be able to safely omit CURRENTYEAR from pelicanconf.py

**Comment by dfoulks1** [comment]
if it's a trivial fix I'm not opposed, but why not just fix the templates?

**Comment by gstein** [comment]
Please provide a PR if this concerns you.
